/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:66f7e24b-7e56-4ce8-8514-738479d82aaf",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_ZCXHvN6Q2",
    "aws_user_pools_web_client_id": "tdq4u2g2aha6nbnmaisgs8ss8",
    "oauth": {}
};


export default awsmobile;
